apiVersion: v1
kind: Service
metadata:
  name: my-deployment-site
spec:
  selector:
    app: my-app-name
  ports:
  - protocol: TCP
    port: 30080
    targetPort: 80
    nodePort: 30080
  type: NodePort
